### ISSUE TITLE
SW Map Request

### ISSUE THREAD

**Issue by KateTheCat** [altonchaney/star-wars-galaxy-maps#1]
Not an issue, but do you plan to include the paths of characters from SW Rebels in your maps? If not, can I ask where you got your data for the Bad Batch series? I've been looking for a list of planets visited in SW Rebels for a while. Do you just take notes while watching, or is there a list somewhere?

Also, the "Having issues? Submit them here" link on the website takes you to the Cosmere map project instead of this one.

**Comment by altonchaney** [comment]
Yeah I do plan on adding Rebels soon, usually I pick these off as I actually watch the series and consult Wookiepedia, but I haven't circled back in a while. I've updated the link in this project as well, thank you for calling that out.
